\documentclass{article}

\usepackage{listings}
\usepackage{color}

\definecolor{dkgreen}{rgb}{0,0.6,0}
\definecolor{gray}{rgb}{0.5,0.5,0.5}
\definecolor{mauve}{rgb}{0.58,0,0.82}

\lstset{frame=tb,
  language=Java,
  aboveskip=3mm,
  belowskip=3mm,
  showstringspaces=false,
  columns=flexible,
  basicstyle={\small\ttfamily},
  numbers=none,
  numberstyle=\tiny\color{gray},
  keywordstyle=\color{blue},
  commentstyle=\color{dkgreen},
  stringstyle=\color{mauve},
  breaklines=true,
  breakatwhitespace=true,
  tabsize=3
}

\begin{document}
\SweaveOpts{concordance=TRUE}


<<echo=TRUE>>=
result <- Clustering::clustering(df = Clustering::basketball, min = 3, max = 5, algorithm = c('gmm', 'fanny'), metrics = c('entropy','dunn'))
@

<<echo=TRUE>>=
Clustering::evaluate_best_validation_external_by_metrics(result)
@

<<echo=TRUE>>=
Clustering::plot_clustering(result,'entropy')
@




\end{document}
